/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonProfileManagement;

import java.awt.CardLayout;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;
import ui.PersonProfileManagement.PersonProfileMngJPanel;
import ui.PersonProfileManagement.ManagePeopleJPanel;

/**
 *
 * @author Pragna Balaji Rao
 */
public class PersonProfileMngJPanel extends javax.swing.JPanel {
    
    JPanel personManagementContainer;
    PersonDirectory personDirectory;
    List<Person> foundPersons;
    

    /**
     * Creates new form PersonProfileMngJPanel
     */
    public PersonProfileMngJPanel(JPanel container,PersonDirectory directory) {
        initComponents();
        
        this.personManagementContainer = container;
        this.personDirectory = directory;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManage = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblquestion = new javax.swing.JLabel();
        btnList = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        btnManage.setBackground(new java.awt.Color(153, 153, 255));
        btnManage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnManage.setText("Manage People Profiles");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(153, 153, 255));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreate.setText("Add New Person");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblquestion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblquestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblquestion.setText("What would you like to do today?");

        btnList.setBackground(new java.awt.Color(153, 153, 255));
        btnList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnList.setText("List People Profiles");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblquestion)
                    .addComponent(btnManage, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblquestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreate)
                .addGap(30, 30, 30)
                .addComponent(btnManage)
                .addGap(26, 26, 26)
                .addComponent(btnList)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        CreatePersonProfileJPanel panel = new CreatePersonProfileJPanel(personManagementContainer, personDirectory);
        personManagementContainer.add("CreateProfileJPanel",panel);
        
        CardLayout layout = (CardLayout) personManagementContainer.getLayout();
        layout.next(personManagementContainer);
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        
        ManagePeopleJPanel panel = new ManagePeopleJPanel(personManagementContainer, personDirectory);
        personManagementContainer.add("ManagePeopleJPanel ",panel);
        
        CardLayout layout = (CardLayout) personManagementContainer.getLayout();
        layout.next(personManagementContainer);
        
       
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        
        ListPeopleProfilesJPanel panel = new ListPeopleProfilesJPanel(personManagementContainer, personDirectory );
        personManagementContainer.add("ListPeopleProfilesJPanel", panel);

        
        CardLayout layout = (CardLayout) personManagementContainer.getLayout();
        layout.next(personManagementContainer);
        
        
    }//GEN-LAST:event_btnListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnManage;
    private javax.swing.JLabel lblquestion;
    // End of variables declaration//GEN-END:variables
}
