/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonProfileManagement;

import model.*;
import model.Person;
import model.Address;
import model.PersonDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pragna Balaji Rao
 */
public class viewPeopleProfilesJPanel extends javax.swing.JPanel {
    
    private JPanel personManagementContainer;
    private PersonDirectory personDirectory;
    private Person person;


    /**
     * Creates new form viewPeopleProfilesJPanel
     */
    public viewPeopleProfilesJPanel(JPanel personManagementContainer, PersonDirectory directory, Person person ) {
        initComponents();
        
        this.personManagementContainer = personManagementContainer;
        this.personDirectory = personDirectory;
        this.person = person;
        
        if (this.person == null) {
        JOptionPane.showMessageDialog(null, "Person profile is null. Please select a valid profile.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        refreshTextFields();
        setViewMode();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTtitle = new javax.swing.JLabel();
        txtWCity = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblWorkAddress = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblWStreetAddress = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWUnitNumber = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        lblGenInfo = new javax.swing.JLabel();
        llblWState = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        lblWZipCode = new javax.swing.JLabel();
        txtHStreetAddress = new javax.swing.JTextField();
        txtWZipCode1 = new javax.swing.JTextField();
        txtHUnitNumber = new javax.swing.JTextField();
        lblHStreetAddress = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHUnitNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtHCity = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblHState = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtHZipCode = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblHCity = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtHState = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblHZipCode = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtWStreet = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtWUnitNumber = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTtitle.setBackground(new java.awt.Color(51, 0, 204));
        lblTtitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTtitle.setText(" Person Profile Display");
        lblTtitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTtitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblWorkAddress.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblWorkAddress.setForeground(new java.awt.Color(51, 51, 255));
        lblWorkAddress.setText("Work Address");

        lblWStreetAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWStreetAddress.setText("Street");

        lblHeight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHeight.setText("Height");

        lblWUnitNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWUnitNumber.setText("Unit Number");

        lblWeight.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWeight.setText("Weight");

        lblWCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWCity.setText("City");

        lblGenInfo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblGenInfo.setForeground(new java.awt.Color(51, 51, 255));
        lblGenInfo.setText("General Information");

        llblWState.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        llblWState.setText("State");

        lblHomeAddress.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(51, 51, 255));
        lblHomeAddress.setText("Home Address");

        lblWZipCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWZipCode.setText("Zip Code");

        lblHStreetAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHStreetAddress.setText("Street");

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHUnitNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHUnitNumber.setText("Unit Number");

        lblHState.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHState.setText("State");

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastName.setText("Last Name");

        lblHCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHCity.setText("City");

        lblSSN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSSN.setText("SSN");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setText("Age");

        lblHZipCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHZipCode.setText("Zip Code");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setText("Gender");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhoneNumber.setText("Phone Number");

        btnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(150, 150, 150)
                        .addComponent(lblTtitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGenInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSSN)
                            .addComponent(lblPhoneNumber)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHeight)
                                    .addComponent(lblGender)
                                    .addComponent(txtGender)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblWeight)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHomeAddress)
                                .addGap(86, 86, 86)
                                .addComponent(lblWorkAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblHUnitNumber)
                                        .addComponent(lblHState)
                                        .addComponent(lblHStreetAddress)
                                        .addComponent(lblHZipCode)
                                        .addComponent(lblHCity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHState)
                                        .addComponent(txtHCity)
                                        .addComponent(txtHUnitNumber)
                                        .addComponent(txtHStreetAddress)
                                        .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(llblWState)
                                    .addComponent(lblWStreetAddress)
                                    .addComponent(lblWUnitNumber)
                                    .addComponent(txtWStreet)
                                    .addComponent(txtWUnitNumber)
                                    .addComponent(lblWCity)
                                    .addComponent(txtWCity)
                                    .addComponent(txtWZipCode1)
                                    .addComponent(lblWZipCode)
                                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(53, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTtitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGenInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSSN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPhoneNumber)
                        .addGap(0, 0, 0)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAge)
                        .addGap(7, 7, 7)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHomeAddress)
                            .addComponent(lblWorkAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWStreetAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblWUnitNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(llblWState)
                                .addGap(0, 0, 0)
                                .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblWZipCode))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHStreetAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHUnitNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHState)
                                .addGap(0, 0, 0)
                                .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHZipCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWZipCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(btnSave))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        // Remove the current panel from the container
        personManagementContainer.remove(this);

        // Get the last panel from the stack
        Component[] panelStack = personManagementContainer.getComponents();
        if (panelStack.length > 0) {
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];

            // Check if the last panel is of type ManagePeopleJPanel
            if (lastPanel instanceof ManagePeopleJPanel) {
            ManagePeopleJPanel managePeoplePanel = (ManagePeopleJPanel) lastPanel;
            managePeoplePanel.populateTable(); // Refresh data on the Manage panel
        } else if (lastPanel instanceof ListPeopleProfilesJPanel) {
            ListPeopleProfilesJPanel listPeoplePanel = (ListPeopleProfilesJPanel) lastPanel;
            
        }
    }

    // Navigate to the previous panel
    CardLayout layout = (CardLayout) personManagementContainer.getLayout();
    layout.previous(personManagementContainer);

                                      
       
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String FirstName = txtFirstName.getText();
        String LastName = txtLastName.getText();
        String SocialSecurityNumber = txtSSN.getText();
        String HStreetAddress = txtHStreetAddress.getText();
        String WStreet = txtWStreet.getText();
        String HState = txtHState.getText();
        String WState = txtWState.getText();
        String HCity = txtHCity.getText();
        String WCity = txtWCity.getText();
        
        int age = Integer.parseInt(txtAge.getText());
        int homeUnitNumber = Integer.parseInt(txtHUnitNumber.getText());
        int homeZipCode = Integer.parseInt(txtHZipCode.getText());
        int workUnitNumber = Integer.parseInt(txtWUnitNumber.getText());
        int workZipCode = Integer.parseInt(txtWZipCode1.getText());
        
        double height = Double.parseDouble(txtHeight.getText());
        float weight = Float.parseFloat(txtWeight.getText());
        
        
        if (FirstName.isBlank() || LastName.isBlank() || SocialSecurityNumber.isBlank() || HStreetAddress.isBlank() || WStreet.isBlank() || HState.isBlank() || WState.isBlank() || HCity.isBlank() || WCity.isBlank()) 
        {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
            return;
        }
        if (person != null) {
        person.setFirstName(FirstName);
        person.setLastName(LastName);
        person.setSocialSecurityNumber(SocialSecurityNumber);
        person.setHomeStreetAddress(HStreetAddress);
        person.setHomeCity(HCity);
        person.setHomeState(HState);
        person.setWorkStreetAddress(WStreet);
        person.setWorkCity(WCity);
        person.setWorkState(WState);
        person.setHeight(height);
        person.setWeight(weight);
        person.setHomeUnitNumber(homeUnitNumber);
        person.setWorkUnitNumer(workUnitNumber);
        person.setHomeZipCode(homeZipCode);
        person.setWorkZipCode(workZipCode);
        person.setAge(age);


        
        JOptionPane.showMessageDialog(null, "Account sucessfully updated!", "WARNING", JOptionPane.WARNING_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "No account selected. Please select an account first.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGenInfo;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHStreetAddress;
    private javax.swing.JLabel lblHUnitNumber;
    private javax.swing.JLabel lblHZipCode;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTtitle;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWStreetAddress;
    private javax.swing.JLabel lblWUnitNumber;
    private javax.swing.JLabel lblWZipCode;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel llblWState;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHStreetAddress;
    private javax.swing.JTextField txtHUnitNumber;
    private javax.swing.JTextField txtHZipCode;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWStreet;
    private javax.swing.JTextField txtWUnitNumber;
    private javax.swing.JTextField txtWZipCode1;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtSSN.setText(person.getSocialSecurityNumber());
        txtHStreetAddress.setText(person.getAddress().getHomstreetAddress());
        txtWStreet.setText(person.getAddress().getWorkStreetAddress());
        txtHState.setText(person.getAddress().getHomeState());
        txtWState.setText(person.getAddress().getWorkState());
        txtHCity.setText(person.getAddress().getHomeState());
        txtWCity.setText(person.getAddress().getWorkCity());
        txtHUnitNumber.setText(String.valueOf(person.getAddress().getHomeUnitNumber())); 
        txtWUnitNumber.setText(String.valueOf(person.getAddress().getWorkUnitNumber()));
        txtHZipCode.setText(String.valueOf(person.getAddress().getHomeZipCode())); // Convert zip code to String
        txtWZipCode1.setText(String.valueOf(person.getAddress().getWorkZipCode())); // Convert work zip code to String
        txtPhoneNumber.setText(String.valueOf(person.getPhoneNumber()));
        txtAge.setText(String.valueOf(person.getAge()));
        txtHeight.setText(String.valueOf(person.getHeight()));
        txtWeight.setText(String.valueOf(person.getWeight()));
        txtGender.setText(Character.toString(person.getGender()));
        

        
    }

    private void setViewMode() {
        
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSSN.setEnabled(true);
        txtPhoneNumber.setEnabled(true);
        txtAge.setEnabled(true);
        txtGender.setEnabled(true);
        txtHeight.setEnabled(true);
        txtWeight.setEnabled(true);
        txtHStreetAddress.setEnabled(true);
        txtHUnitNumber.setEnabled(true);
        txtHCity.setEnabled(true);
        txtHState.setEnabled(true);
        txtHZipCode.setEnabled(true);
        txtWStreet.setEnabled(true);
        txtWUnitNumber.setEnabled(true);
        txtWCity.setEnabled(true);
        txtWState.setEnabled(true);
        txtWZipCode1.setEnabled(true);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
    }

    private void setEditMode() {
        
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSSN.setEnabled(true);
        txtPhoneNumber.setEnabled(true);
        txtAge.setEnabled(true);
        txtGender.setEnabled(true);
        txtHeight.setEnabled(true);
        txtWeight.setEnabled(true);
        txtHStreetAddress.setEnabled(true);
        txtHUnitNumber.setEnabled(true);
        txtHCity.setEnabled(true);
        txtHState.setEnabled(true);
        txtHZipCode.setEnabled(true);
        txtWStreet.setEnabled(true);
        txtWUnitNumber.setEnabled(true);
        txtWCity.setEnabled(true);
        txtWState.setEnabled(true);
        txtWZipCode1.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
}
